In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.arange(1,100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [26]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [30]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [31]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [32]:
myarr.shape

(4, 3)

In [33]:
myarr.size

12

In [34]:
myarr.ndim

2

In [35]:
myarr.dtype

dtype('int64')

In [40]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32')

In [41]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [43]:
n= myarr.astype('float64')

In [44]:
n.dtype

dtype('float64')

In [45]:
myarr.dtype

dtype('float32')