In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat[3:6]

array([4, 5, 6])

In [11]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[::6]

array([1, 7])

In [14]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [18]:
b = flat[3:7].copy() # This is not a slice cuz we are using the copy function

In [19]:
b

array([4, 5, 6, 7])