In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.sum(arr,axis=0)) # Sum along rows (down each column)

[12 15 18]


In [5]:
print(np.sum(arr,axis=1)) # Sum along colums (across each rows)

[ 6 15 24]


In [6]:
# Acessing an element
print(arr[1,2]) 

6


In [7]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


In [8]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [9]:
print(arr3D.shape)

(2, 2, 3)


In [10]:
print(arr3D[0,1,2])

6


In [11]:
print(arr3D[:,0,:]) # depth, row, colum

[[1 2 3]
 [7 8 9]]


In [12]:
first_col = arr[:,0]
print(first_col)

[1 4 7]


In [13]:
first_row = arr3D[:,0,:]
print(first_row)

[[1 2 3]
 [7 8 9]]


In [16]:
arr[:,1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
